title: office.com/setup - www.office.com/setup/activationkey
description: The office home and student 2019 is free for the students and also provides free 1TB online storage for students and teachers only. 

theme: jekyll-theme-cayman